package csci812_project.backend.entity;

import csci812_project.backend.enums.AccountType;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "accounts")
public class Account {

    /**
     * Unique account ID (Primary Key).
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "account_id")
    private Long accountId;

    /**
     * Foreign Key linking this account to a user.
     * Ensures that each account belongs to a specific user.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Name of the account (e.g., "Savings Account", "Personal Wallet").
     * Required field.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotBlank(message = "Account name is required")
    private String name;

    /**
     * Type of the account.
     * Must be one of the predefined ENUM values.
     */
    @Column(name = "type", nullable = false)
    @Enumerated(EnumType.STRING)
    private AccountType type;

    /**
     * Current balance in the account.
     * Cannot be negative.
     * Default value is 0.00.
     */
    @Column(name = "balance", nullable = false, precision = 15, scale = 2)
    @DecimalMin(value = "0.00", message = "Balance cannot be negative")
    private BigDecimal balance = BigDecimal.ZERO;

    /**
     * Currency code (ISO 4217 format, e.g., "USD", "EUR").
     * Defaults to "USD".
     */
    @Column(name = "currency", nullable = false, length = 3)
    @Pattern(regexp = "^[A-Z]{3}$", message = "Currency must be a valid 3-letter ISO code")
    private String currency = "USD";

    /**
     * Name of the financial institution (e.g., "Bank of America").
     * Optional field.
     */
    @Column(name = "institution_name", length = 100)
    private String institutionName;

    /**
     * Account number for bank accounts.
     * Must be unique.
     */
    @Column(name = "account_number", unique = true, length = 50)
    private String accountNumber;

    /**
     * Interest rate applicable to the account (if any).
     * Cannot be negative.
     */
    @Column(name = "interest_rate", precision = 5, scale = 2)
    @DecimalMin(value = "0.00", message = "Interest rate cannot be negative")
    private BigDecimal interestRate;

    /**
     * Marks whether this is the default account for the user.
     * Defaults to false.
     */
    @Column(name = "is_default", nullable = false)
    private boolean isDefault = false;

    /**
     * Soft delete flag to prevent accidental deletion.
     * Instead of removing the account, set this flag to TRUE.
     */
    @Column(name = "is_deleted", nullable = false)
    private boolean isDeleted = false;

    /**
     * Timestamp for when the account was created.
     * Automatically set when a new record is inserted.
     */
    @Column(name = "date_created", updatable = false)
    private LocalDateTime dateCreated = LocalDateTime.now();

    /**
     * Timestamp for when the account was last updated.
     * Automatically updates on modification.
     */
    @Column(name = "date_updated")
    private LocalDateTime dateUpdated = LocalDateTime.now();

    /**
     * Lifecycle hook to update the timestamp before updating.
     */
    @PreUpdate
    protected void onUpdate() {
        this.dateUpdated = LocalDateTime.now();
    }

    // Constructor
public Account(){}
    public Account(Long accountId, User user, String name, AccountType type, BigDecimal balance, String currency, String institutionName,
                   String accountNumber, BigDecimal interestRate, boolean isDefault, boolean isDeleted, LocalDateTime dateCreated, LocalDateTime dateUpdated) {
        this.accountId = accountId;
        this.user = user;
        this.name = name;
        this.type = type;
        this.balance = balance;
        this.currency = currency;
        this.institutionName = institutionName;
        this.accountNumber = accountNumber;
        this.interestRate = interestRate;
        this.isDefault = isDefault;
        this.isDeleted = isDeleted;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
    }

    // Getter and Setter

    public Long getAccountId() {
        return accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public @NotBlank(message = "Account name is required") String getName() {
        return name;
    }

    public void setName(@NotBlank(message = "Account name is required") String name) {
        this.name = name;
    }

    public AccountType getType() {
        return type;
    }

    public void setType(AccountType type) {
        this.type = type;
    }

    public @DecimalMin(value = "0.00", message = "Balance cannot be negative") BigDecimal getBalance() {
        return balance;
    }

    public void setBalance(@DecimalMin(value = "0.00", message = "Balance cannot be negative") BigDecimal balance) {
        this.balance = balance;
    }

    public @Pattern(regexp = "^[A-Z]{3}$", message = "Currency must be a valid 3-letter ISO code") String getCurrency() {
        return currency;
    }

    public void setCurrency(@Pattern(regexp = "^[A-Z]{3}$", message = "Currency must be a valid 3-letter ISO code") String currency) {
        this.currency = currency;
    }

    public String getInstitutionName() {
        return institutionName;
    }

    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public @DecimalMin(value = "0.00", message = "Interest rate cannot be negative") BigDecimal getInterestRate() {
        return interestRate;
    }

    public void setInterestRate(@DecimalMin(value = "0.00", message = "Interest rate cannot be negative") BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    public boolean isDefault() {
        return isDefault;
    }

    public void setDefault(boolean aDefault) {
        isDefault = aDefault;
    }

    public boolean isDeleted() {
        return isDeleted;
    }

    public void setDeleted(boolean deleted) {
        isDeleted = deleted;
    }

    public LocalDateTime getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(LocalDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    public LocalDateTime getDateUpdated() {
        return dateUpdated;
    }

    public void setDateUpdated(LocalDateTime dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
}

